### ISSUE TITLE
1주차 필수과제

### ISSUE THREAD

**Issue by l2zh** [DO-SOPT-ANDROID/junhee-lee#1]
## ❗ 이슈 요약

로그인,회원가입,마이페이지 구현

## 📝 todo

- [x] 로그인 페이지 구현
- [x] 회원가입 페이지 구현
- [x] 메인 페이지 구현
