### ISSUE TITLE
3주차 도전과제

### ISSUE THREAD

**Issue by l2zh** [DO-SOPT-ANDROID/junhee-lee#15]
## ❗ 이슈 요약

3주차 도전과제

## 📝 todo

- [ ] 다크 모드 대응 (sdk 버전에 따른 분기처리)
- [ ] Material Design 2,3 차이점 정리
- [ ] 커스텀 뷰 구현 후 과정 정리
