### ISSUE TITLE
2주차 심화 과제

### ISSUE THREAD

**Issue by l2zh** [DO-SOPT-ANDROID/junhee-lee#8]
## ❗ 이슈 요약

심화과제 구현

## 📝 todo

- [x] Fragment 생명주기 공부
- [x] BottomNavigation 보수 (ripple, icon Tint, 첫 진입시 Do Android 나오게)
- [x] BottomNavigation 동일한 탭 더블 터치시 앱 최상단으로 이동
- [x] ListAdapter 적용
