### ISSUE TITLE
2주차 도전 과제

### ISSUE THREAD

**Issue by l2zh** [DO-SOPT-ANDROID/junhee-lee#9]
## ❗ 이슈 요약

도전과제 구현

## 📝 todo

- [x] 가로모드 시에도 앱 안터지게 하기
- [x] 가로모드에서 ViewPager로 친구목록 보여주기
- [x] 리스트 세부 정보 확인 구현
- [x] Floating Action 추가하고 친구 목록에 친구 추가 기능 구현
- [x] 친구 목록에서 친구 삭제 기능 구현
